### ISSUE TITLE
Ajouter des liens de partage sur les réseaux sociaux

### ISSUE THREAD

**Issue by emchateau** [emchateau/ahaWeb#16]
Pour augmenter l’intégration avec les réseaux sociaux, ajouter un module de partage.
- [ ] lister les modules pertinents
- [ ] choisir le module
- [ ] implémenter le module
- [ ] unifier graphiquement

**Comment by LeonoreLosserand** [comment]
facebook
twitter
youtube ?
google+
linkedin
viméo ?

**Comment by emchateau** [comment]
done pour fb tw et viméo, il me semble que cela suffit.
cf. #18
