### ISSUE TITLE
Préparer la refonte graphique du site

### ISSUE THREAD

**Issue by emchateau** [emchateau/ahaWeb#2]
La refonte du site web de l’association nécessite au préalable la définition d’une politique éditoriale claire.

- [x] clarifier le niveau d’intégration avec les réseaux sociaux
- [x] déterminer les rôles des utilisateurs
- [x] ...

**Comment by LeonoreLosserand** [comment]
thème choisi par JBM : hueman

**Comment by emchateau** [comment]
done
